# Generated by Django 5.2.8 on 2025-12-04 20:41

import django.db.models.deletion
import django.utils.timezone
import student_attendance_interfaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("COET", "Computer Engineering and IT"),
                            ("BIT", "Business Information Technology"),
                            ("BA", "Business Administration"),
                        ],
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_name", models.CharField(max_length=200)),
                ("session_date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="student_attendance_interfaces.course",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_sessions",
                "ordering": ["-session_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="student_attendance_interfaces.course",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["course", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teachers",
            },
        ),
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="absent",
                        max_length=10,
                    ),
                ),
                ("recognized_at", models.DateTimeField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "recognized_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="recognized_faces/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_logs",
                        to="student_attendance_interfaces.attendancesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="student_attendance_interfaces.student",
                    ),
                ),
            ],
            options={
                "db_table": "session_logs",
                "ordering": ["-recognized_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="session_log_session_a23cff_idx",
                    ),
                    models.Index(
                        fields=["student", "session"],
                        name="session_log_student_c87e3c_idx",
                    ),
                ],
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="FaceImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "angle",
                    models.CharField(
                        choices=[
                            ("front", "Front Face"),
                            ("left", "Left Side"),
                            ("right", "Right Side"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=student_attendance_interfaces.models.student_image_path
                    ),
                ),
                ("face_encoding", models.BinaryField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_images",
                        to="student_attendance_interfaces.student",
                    ),
                ),
            ],
            options={
                "db_table": "face_images",
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "angle", "is_active"],
                        name="face_images_student_429d33_idx",
                    ),
                    models.Index(fields=["angle"], name="face_images_angle_aaaec8_idx"),
                ],
            },
        ),
    ]
